remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Welcome to the JFdelaFuente's homepage!
description: Some basic examples of client interfaces to a computer vision API.

author:
  name: JFdelaFuente
